### ISSUE TITLE
Using 'size' and 'blocksize' settings leads to partial read/write on zerodb-thin-backup

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/qemu#1]
**Description**
Using `size` and `blocksize` params lead to an I/O errors. When I run the same command without them, everything is going fine.

**Pre-condition**
- Compile `qemu` from `zerodb-thin-backup` branch
- Run a zdb server

**Steps**
- Start an ubuntu machine using a command like the following one
```bash
qemu-system-x86_64 -boot d -vnc :0 -display none -m 5120 -enable-kvm -cpu host -cdrom /opt/code/ubuntu-16.04.4-desktop-amd64.iso -serial null -serial mon:stdio -drive driver=zdb,port=9900,namespace=ns3,size=10G,blocksize=8k
```
- Connect to the machine using vnc client
- Try to create a partation table using `fdisk /dev/sda` > I coudn't
- Try to create a partation table using `Gparted` toole > Done
- Try to do `mount /dev/sda1 /mnt/sda` 

**Actual result**
![image](https://user-images.githubusercontent.com/17981089/41224353-8d73fc8e-6d6c-11e8-8863-04f837186596.png)

**Comment by maxux** [comment]
After investigation and more deep check, this is a confirmed regression from `zerodb` to `zerodb-thin-backup`, whole blocks are not read when requested.

**Comment by 0xIslamTaha** [comment]
Verified.

commit : `12edbef27f471dc4026736adff3203c3ac2eaab6`
